name: Blogger Indexer & Lockfile Management (Yarn Fix)

on:
  schedule:
    - cron: '0 */1 * * *' 
  workflow_dispatch: 
  push:
    branches:
      - main 
    paths:
      - 'package.json' 

jobs:
  # 1. Setup, Lockfile Management (Yarn ka istemal)
  setup-and-install:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔑 CHANGE: Node.js ke sath Yarn ko bhi set up karen
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn' # Ab yarn cache istemal karen

      - name: Install dependencies (Creates/Updates yarn.lock)
        # 🔑 FIX: Yarn install istemal karen. Ye integrity issues ko handle karega.
        # Agar package-lock.json maujood ho to use delete kar den
        run: yarn install --immutable false

      - name: Commit lockfile (yarn.lock)
        # Yarn.lock ko commit karega
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): Auto-update yarn.lock (Fixing Integrity)"
          files: yarn.lock


  # 2. Indexing Bot ko chalayein
  index-posts:
    runs-on: ubuntu-latest
    needs: setup-and-install
    
    steps:
      - name: Checkout code (After lockfile update)
        uses: actions/checkout@v4

      # 🔑 CHANGE: Node.js ke sath Yarn ko set up karen
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Install Dependencies (Fast install using yarn.lock)
        # Dependencies install karein (yarn install ya yarn)
        run: yarn install --immutable # Tez aur mutabqat wala install
        
      - name: Run Indexing Bot
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          BLOG_URL: ${{ secrets.BLOG_URL }}
        run: node index.js
