name: Blogger Auto Indexer

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Manual trigger
  push:
    branches: [ main ]

jobs:
  index-posts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Blogger Indexer
      env:
        GITHUB_ACTIONS: 'true'
        GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
        GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        BLOG_URL: ${{ secrets.BLOG_URL }}
        RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
        MAX_URLS_PER_RUN: '10' # GitHub Actions ke liye limit
      run: npm start
      
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          console.log('Workflow failed!');
