name: Blogger Auto Indexer

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  index-posts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
      
    - name: Install dependencies
      run: npm install
      
    - name: Run Indexer
      env:
        GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
        GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        BLOG_URL: ${{ secrets.BLOG_URL }}
        RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
      run: node index.js
