name: Scheduled Google Indexing
on:
  schedule:
    - cron: '0 */3 * * *'  # Har 3 ghante
  workflow_dispatch:  # Manual trigger

jobs:
  index-posts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create package.json if missing
        run: |
          if [ ! -f package.json ]; then
            echo '{
              "name": "blogger-auto-indexer",
              "version": "1.0.0",
              "description": "Auto Google Indexing for Blogger Posts",
              "main": "index.js",
              "scripts": {
                "start": "node index.js"
              },
              "dependencies": {
                "googleapis": "^126.0.1",
                "node-cron": "^3.0.2",
                "axios": "^1.5.0",
                "rss-parser": "^3.13.0"
              }
            }' > package.json
          fi

      - name: Install dependencies
        run: npm install

      - name: Run Indexing
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          BLOG_URL: ${{ secrets.BLOG_URL }}
        run: node index.js
