name: Blogger Indexer & Lockfile Management

on:
  schedule:
    # Har 3 ghante mein chalega (Best practice)
    - cron: '0 */3 * * *' 
  workflow_dispatch: # Manual run
  push:
    branches:
      - main # Ya apni branch ka naam
    paths:
      - 'package.json' # package.json badalne par lockfile update ho

jobs:
  # 1. Lockfile aur Dependencies Manage karein
  setup-and-install:
    runs-on: ubuntu-latest
    
    # Commit karne ke liye zaroori permission
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (No Cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Cache ko hata dia taake integrity issue na aaye

      - name: Install dependencies (Creates/Updates package-lock.json & Cleans Cache)
        # 🔑 FIX: --no-cache istemal karen aur --network-concurrency 1
        # Ye Integrity issue aur network corruption ko hal karega
        run: npm install --no-cache --network-concurrency 1

      - name: Commit package-lock.json (If changed or created)
        # Nayi ya updated lockfile ko repository mein commit karega
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): Auto-update package-lock.json"
          files: package-lock.json


  # 2. Indexing Bot ko chalayein
  index-posts:
    runs-on: ubuntu-latest
    # Ye job sirf scheduled run ya manual run par chalni chahiye.
    # Agar sirf indexing bot chalana hai to 'needs: setup-and-install' ko remove karna parhega.
    # Lekin behtar hai ke needs ko rehne den taake dependencies tayyar hon.
    needs: setup-and-install
    
    steps:
      - name: Checkout code (After lockfile update)
        uses: actions/checkout@v4

      - name: Setup Node.js (For Indexer Run)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Dependencies (Fast install using the new lockfile)
        # Ab lockfile maujood hai to npm ci tez chalega
        run: npm ci 
        
      - name: Run Indexing Bot
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          BLOG_URL: ${{ secrets.BLOG_URL }}
        # Index.js mein OpenSSL fix maujood hai
        run: node index.js
