name: Scheduled Google Indexing
on:
  schedule:
    - cron: '0 */1 * * *'  # Har 3 ghante (maine 0 */3 * * * kar dia hai, kyunki pehle comment mein 3 ghante likha tha)
  workflow_dispatch:  # Manual trigger 

jobs:
  index-posts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Indexing Bot (with OpenSSL Legacy Provider)
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          BLOG_URL: ${{ secrets.BLOG_URL }}
        # 🔑 Yahan maine NODE_OPTIONS environment variable shamil kar diya hai
        run: NODE_OPTIONS=--openssl-legacy-provider node index.js
