name: Blogger Indexer & Lockfile Management

on:
  schedule:
    # Indexing Bot har 3 ghante mein chalega
    - cron: '0 */1 * * *' 
  workflow_dispatch: # Manual run ke liye
  push:
    branches:
      - main # Apni branch ka naam
    paths:
      # package.json badalne par Lockfile update ho
      - 'package.json' 

jobs:
  # 1. Setup, Lockfile Management, aur Dependencies Install
  setup-and-install:
    runs-on: ubuntu-latest
    
    # Commit karne ke liye zaroori permission
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (No Cache)
        # Cache ko hata dia taake integrity issue na aaye
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Fix Integrity Error)
        # 🔑 FIX: --force option istemal karen taake integrity error ko ignore kia ja sake
        run: npm install --no-cache --network-concurrency 1 --force

      - name: Commit package-lock.json (If created/changed)
        # Nayi ya updated lockfile ko repository mein commit karega
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): Auto-update package-lock.json"
          files: package-lock.json


  # 2. Indexing Bot ko chalayein (Dependencies install hone ke baad)
  index-posts:
    runs-on: ubuntu-latest
    # Ye job sirf tab chalegi jab 'setup-and-install' job kamyab ho
    needs: setup-and-install
    
    steps:
      - name: Checkout code (After lockfile update)
        # Zaroori hai taake naya 'package-lock.json' is job mein maujood ho
        uses: actions/checkout@v4

      - name: Setup Node.js (For Indexer Run)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Dependencies (Fast install using the new lockfile)
        # Lockfile ban chuka hai to npm ci istemal karen
        run: npm ci 
        
      - name: Run Indexing Bot
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          BLOG_URL: ${{ secrets.BLOG_URL }}
        # Index.js mein OpenSSL fix maujood hai
        run: node index.js
