name: Scheduled Google Indexing
on:
  schedule:
    - cron: '0 */3 * * *'  # Har 3 ghante
  workflow_dispatch:  # Manual trigger

jobs:
  index-posts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          # Create package-lock.json if not exists
          if [ ! -f package-lock.json ]; then
            npm init -y
          fi

      - name: Run Indexing
        env:
          # Indexing API ke liye (Service Account)
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          
          # Blog details
          BLOG_URL: ${{ secrets.BLOG_URL }}
          RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }} # Optional
        run: node index.js
