name: Update package-lock.json

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  update-lock:
    runs-on: ubuntu-latest
    
    # 🔑 FIX: Permissions yahan shamil karen
    permissions:
      contents: write # Ye permission file ko commit aur push karne ke liye zaroori hai
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies (This generates package-lock.json)
        run: npm install
        
      - name: Commit package-lock.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): Auto-generate package-lock.json"
          files: package-lock.json
